/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ntomura1' at '15/12/21 23:57' with Gradle 2.8
 *
 * @author ntomura1, @date 15/12/21 23:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
